"""PDF export service for generating downloadable PDFs from content."""

import base64
import io
import logging
import re
from datetime import datetime

import markdown
from weasyprint import HTML, CSS

logger = logging.getLogger(__name__)

PDF_STYLES = """
@page {
    size: letter;
    margin: 1in;
    @bottom-center {
        content: counter(page);
        font-size: 10pt;
        color: #666;
    }
}

body {
    font-family: 'Georgia', 'Times New Roman', serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #333;
}

h1 {
    font-size: 24pt;
    color: #1a1a1a;
    margin-top: 0;
    margin-bottom: 24pt;
    page-break-after: avoid;
    border-bottom: 2px solid #333;
    padding-bottom: 12pt;
}

h2 {
    font-size: 18pt;
    color: #2a2a2a;
    margin-top: 24pt;
    margin-bottom: 12pt;
    page-break-after: avoid;
}

h3 {
    font-size: 14pt;
    color: #3a3a3a;
    margin-top: 18pt;
    margin-bottom: 10pt;
    page-break-after: avoid;
}

p {
    margin: 0 0 12pt 0;
    text-align: justify;
}

blockquote {
    margin: 16pt 0;
    padding: 12pt 20pt;
    background-color: #f9f9f9;
    border-left: 4px solid #666;
    font-style: italic;
}

ul, ol {
    margin: 12pt 0;
    padding-left: 24pt;
}

li {
    margin-bottom: 6pt;
}

code {
    font-family: 'Courier New', monospace;
    font-size: 10pt;
    background-color: #f4f4f4;
    padding: 2pt 4pt;
    border-radius: 3pt;
}

pre {
    font-family: 'Courier New', monospace;
    font-size: 9pt;
    background-color: #f4f4f4;
    padding: 12pt;
    border-radius: 4pt;
    overflow-x: auto;
    white-space: pre-wrap;
    word-wrap: break-word;
}

img {
    max-width: 100%;
    height: auto;
    display: block;
    margin: 16pt auto;
}

figure {
    margin: 20pt 0;
    text-align: center;
}

figcaption {
    font-size: 10pt;
    color: #666;
    font-style: italic;
    margin-top: 8pt;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin: 16pt 0;
    font-size: 10pt;
}

th, td {
    border: 1px solid #ddd;
    padding: 8pt;
    text-align: left;
}

th {
    background-color: #f4f4f4;
    font-weight: bold;
}

hr {
    border: none;
    border-top: 1px solid #ddd;
    margin: 24pt 0;
}

.chapter-break {
    page-break-before: always;
}

.title-page {
    text-align: center;
    padding-top: 200pt;
}

.title-page h1 {
    font-size: 32pt;
    border: none;
    padding: 0;
}

.title-page .subtitle {
    font-size: 14pt;
    color: #666;
    margin-top: 24pt;
}

.title-page .date {
    font-size: 12pt;
    color: #888;
    margin-top: 48pt;
}

.references {
    font-size: 10pt;
}

.references h1 {
    font-size: 20pt;
}

.references p, .references li {
    margin-bottom: 8pt;
}

a {
    color: #0066cc;
    text-decoration: none;
}

a:hover {
    text-decoration: underline;
}
"""


def embed_images_in_html(html_content: str, visual_assets: list | None = None) -> str:
    """Convert image references to embedded base64 data URIs.

    Args:
        html_content: HTML content with image tags
        visual_assets: List of VisualAsset objects with base64_data

    Returns:
        HTML with embedded images
    """
    if not visual_assets:
        return html_content

    asset_map = {}
    for asset in visual_assets:
        if asset.base64_data and asset.url:
            mime_type = f"image/{asset.format}" if asset.format else "image/png"
            data_uri = f"data:{mime_type};base64,{asset.base64_data}"
            asset_map[asset.url] = data_uri

    def replace_src(match):
        src = match.group(1)
        if src in asset_map:
            return f'src="{asset_map[src]}"'
        return match.group(0)

    return re.sub(r'src="([^"]+)"', replace_src, html_content)


def markdown_to_html(
    chapters: list[dict],
    topic: str,
    references: str | None = None,
    visual_assets: list | None = None,
) -> str:
    """Convert markdown chapters to styled HTML document.

    Args:
        chapters: List of chapter dicts with 'title' and 'content'
        topic: Document topic/title
        references: Optional references section
        visual_assets: Optional visual assets for image embedding

    Returns:
        Complete HTML document
    """
    md = markdown.Markdown(
        extensions=['tables', 'fenced_code', 'nl2br', 'sane_lists'],
        output_format='html'
    )

    html_parts = []

    html_parts.append(f'''
    <div class="title-page">
        <h1>{topic}</h1>
        <div class="subtitle">Generated by Prolific</div>
        <div class="date">{datetime.now().strftime("%B %d, %Y")}</div>
    </div>
    ''')

    for i, chapter in enumerate(chapters):
        chapter_class = "chapter-break" if i > 0 else ""
        title = chapter.get('title', f'Chapter {i + 1}')
        content = chapter.get('content', '')

        html_content = md.convert(content)
        md.reset()

        html_parts.append(f'''
        <div class="{chapter_class}">
            <h1>{title}</h1>
            {html_content}
        </div>
        ''')

    if references:
        html_refs = md.convert(references)
        html_parts.append(f'''
        <div class="chapter-break references">
            <h1>References</h1>
            {html_refs}
        </div>
        ''')

    full_html = f'''
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>{topic}</title>
    </head>
    <body>
        {''.join(html_parts)}
    </body>
    </html>
    '''

    if visual_assets:
        full_html = embed_images_in_html(full_html, visual_assets)

    return full_html


def generate_pdf(
    chapters: list[dict],
    topic: str,
    references: str | None = None,
    visual_assets: list | None = None,
) -> bytes:
    """Generate PDF from markdown chapters.

    Args:
        chapters: List of chapter dicts with 'title' and 'content'
        topic: Document topic/title
        references: Optional references section
        visual_assets: Optional visual assets for image embedding

    Returns:
        PDF file bytes
    """
    html_content = markdown_to_html(
        chapters=chapters,
        topic=topic,
        references=references,
        visual_assets=visual_assets,
    )

    html = HTML(string=html_content)
    css = CSS(string=PDF_STYLES)

    pdf_buffer = io.BytesIO()
    html.write_pdf(pdf_buffer, stylesheets=[css])
    pdf_buffer.seek(0)

    return pdf_buffer.read()


async def export_thread_to_pdf(
    thread_state: dict,
    visual_assets: list | None = None,
) -> bytes:
    """Export a generation thread to PDF.

    Args:
        thread_state: Thread state from checkpointer
        visual_assets: Optional visual assets for image embedding

    Returns:
        PDF file bytes
    """
    topic = thread_state.get('topic', 'Untitled')
    draft_chunks = thread_state.get('draft_chunks', [])
    approved_sources = thread_state.get('approved_sources', [])

    chapters = []
    for chunk in sorted(draft_chunks, key=lambda x: getattr(x, 'chapter_number', 0)):
        chapters.append({
            'chapter_number': getattr(chunk, 'chapter_number', 0),
            'title': getattr(chunk, 'title', f'Chapter {len(chapters) + 1}'),
            'content': getattr(chunk, 'content', ''),
        })

    references = None
    if approved_sources:
        ref_lines = ["\n## Bibliography\n"]
        for i, source in enumerate(approved_sources, 1):
            author = getattr(source, 'author', 'Unknown')
            title = getattr(source, 'title', 'Untitled')
            url = getattr(source, 'url', '')
            pub_date = getattr(source, 'publication_date', None)

            date_str = ""
            if pub_date:
                try:
                    date_str = f" ({pub_date.strftime('%Y')})"
                except:
                    pass

            ref_lines.append(f"{i}. {author}. \"{title}\"{date_str}. {url}\n")

        references = "\n".join(ref_lines)

    state_visual_assets = thread_state.get('visual_assets', [])
    all_assets = list(state_visual_assets) if state_visual_assets else []
    if visual_assets:
        all_assets.extend(visual_assets)

    return generate_pdf(
        chapters=chapters,
        topic=topic,
        references=references,
        visual_assets=all_assets if all_assets else None,
    )
